<h1>717 INTERACTIVE IS ACCEPTING NEW CLIENTS IN OCTOBER</h1>
<h3>A NEW, LIGHTWEIGHT DESIGN STUDIO</h3>
<h2>NICHE 1: CHICAGO NIGHTLIFE WEBSITES</h2>
<h2>NICHE 2: DATA DRIVEN SYSTEMIC VIDEO GAMES </h2>
